apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller
  name: controller-svc
  namespace: ubiquti
spec:
  type: NodePort
  selector:
    app: controller
  ports:
  - name: unifi-stun
    port: 3478
    targetPort: 3478
    nodePort: 3478
    protocol: UDP
  - name: ap-discovery
    port: 10001
    targetPort: 10001
    nodePort: 10001
    protocol: UDP
  - name: device-comm
    port: 8080
    targetPort: 8080
    nodePort: 8080
    protocol: TCP
  - name: unifi-admin
    port: 8443
    targetPort: 8443
    nodePort: 8443
    protocol: TCP
  - name: controller-discoverable-l2
    port: 1900
    targetPort: 1900
    nodePort: 1900
    protocol: UDP
  # - name: guest-portal-redirect-https
  #   port: 8843
  #   targetPort: 8843
  #   nodePort: 8843
  #   protocol: TCP
  # - name: guest-portal-redirect-http
  #   port: 8880
  #   targetPort: 8880
  #   nodePort: 8880
  #   protocol: TCP
  # - name: mobile-throughput-test
  #   port: 6789
  #   targetPort: 6789
  #   nodePort: 6789
  #   protocol: TCP
  # - name: remote-syslog
  #   port: 5514
  #   targetPort: 5514
  #   nodePort: 5514
  #   protocol: TCP
